<?php

/**
 * @file main module file.
 */

use Drupal\commerce_variation_bundle\Entity\VariationBundleInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function commerce_variation_bundle_stock_commerce_product_variation_insert(EntityInterface $entity) {
  if ($entity instanceof VariationBundleInterface) {
     \Drupal::service('commerce_variation_bundle_stock.manager')->setStock($entity);
  }
}


/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function commerce_variation_bundle_stock_commerce_product_variation_presave(EntityInterface $entity) {
  if ($entity instanceof VariationBundleInterface) {
    \Drupal::service('commerce_variation_bundle_stock.manager')->setStock($entity);
  }
}
